apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vishalk17-cluster-demo  # Name of the EKS cluster
  region: ap-south-1            # AWS region
  version: "1.30"               # Kubernetes version

iam:
  withOIDC: true                # Enable OIDC provider

managedNodeGroups:
  - name: my-cluster-demo-ng    # Node group name
    instanceType: t2.medium     # EC2 instance type
    desiredCapacity: 1          # Desired Number of nodes
    minSize: 1                  # Minimum nodes
    maxSize: 1                  # Maximum nodes
    volumeSize: 30              # Disk size in GB
    ssh:
      allow: true               # Enable SSH access
      publicKeyName: vish-console  # Name of the EC2 key pair