apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-pod
  namespace: test-ns
spec:
  serviceAccountName: app-sa
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "3600"]
